# Generated by Django 3.2.5 on 2021-12-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_booking_booker'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='game',
            field=models.CharField(choices=[('2', 'ps3'), ('3', 'ps4'), ('1', 'ps2')], max_length=200, null=True),
        ),
    ]
