# Generated by Django 3.2.5 on 2021-12-30 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_debt_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='debt',
            name='game',
            field=models.CharField(choices=[('ps2', 'ps2'), ('ps3', 'ps3'), ('ps4', 'ps4')], max_length=200, null=True),
        ),
    ]
