# Generated by Django 4.2.7 on 2023-11-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20211230_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='game',
            field=models.CharField(choices=[('ps2', 'ps2'), ('ps4', 'ps4'), ('ps3', 'ps3')], max_length=200, null=True),
        ),
    ]
